Repository BristolSTA/uobtheatre-api, pull requests merged in 2024-10, with the labels that each got.

#820 feat: Implement Turnstile
  config/settings/common.py
  requirements/base.txt
  requirements/local.txt
  schema.graphql
  uobtheatre/users/schema.py
  uobtheatre/users/test/test_schema.py
  uobtheatre/users/test/test_turnstile.py
  uobtheatre/users/turnstile.py
Labels: bug, update front-end, prio:high

#721 feat: Venue-Specific Accessibility Information
  schema.graphql
  uobtheatre/venues/migrations/0005_venue_accessibility_info.py
  uobtheatre/venues/models.py
  uobtheatre/venues/test/test_models.py
Labels: enhancement, update front-end, prio:medium

#720 feat: Production-Wide 'Super' Alerts in Booking Flow
  schema.graphql
  uobtheatre/productions/migrations/0027_production_production_alert.py
  uobtheatre/productions/models.py
Labels: enhancement, update front-end, prio:medium

#719 Add a production filter to the bookings() query
  schema.graphql
  uobtheatre/bookings/schema.py
  uobtheatre/bookings/test/test_schema.py
  uobtheatre/productions/migrations/0027_production_production_alert.py
  uobtheatre/venues/test/test_models.py
Labels: enhancement, update front-end

#836 fix: Expose su_status on SocietyNode and production_alert in ProductionForm
  requirements/local.txt
  schema.graphql
  uobtheatre/productions/forms.py
  uobtheatre/societies/migrations/0007_society_su_status.py
  uobtheatre/societies/schema.py
Labels: bug, prio:high

#851 feat: API work to expose miscCosts for frontend query
  schema.graphql
  uobtheatre/bookings/models.py
  uobtheatre/bookings/schema.py
Labels: enhancement, web companion

#854 repo: Create Repository Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: web companion, repository
